[book]
authors = ["Kisari Mohan Ganguli"]
language = "en"
src = "src"
title = "Mahabharata"
description = "discovering Gita and Maha-bharata"

[output.html]
cname = "mahabharata.shutri.com"
no-section-label = true

[output.html.print]
enable = false    # include support for printable output


